# Generated by Django 5.0 on 2024-08-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTableEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_designation', models.CharField(max_length=255)),
                ('impact', models.FloatField()),
                ('gdpr_compliance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClaimTableOSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_designation', models.CharField(max_length=255)),
                ('impact', models.FloatField()),
                ('gdpr_compliance', models.FloatField()),
            ],
        ),
    ]
